Layout/IndentationWidth:
  Width: 2

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true
